### ISSUE TITLE
Should the expected `Processor` should have access to the current model?

### ISSUE THREAD

**Issue by k0001** [boothead/oHm#2]
Consider the following code:

``` haskell
-- The model
data Model =
  { _modelCurrentUser :: Maybe User
  } _modelInputUsername :: Text

-- Request to change the model
data ModReq
  = ModReqSetInputUsername Text
  | ModReqLogin User

-- Purely modify a model as requested
modReq :: ModReq -> Model -> Model
modReq r m = case r of
    ModReqSetInputUsername t -> m { _modelInputUsername = t }
    ModReqLogin u -> m { _modelCurrentUser = Just u }

-- UI events
data UIEvent
  = UIEventInputUsername Text
  | UIEventLogin Text

-- Processor converting UI events to model change requests.
procUIEvent :: Processor (ReaderT () IO) UIEvent ModReq
procUIEvent = Processor $ \case
    UIEventInputUsername t -> yield $ ModReqSetInputUsername t
    UIEventLogin t -> do
       mu <- liftIO $ getUserByUsername t
       case mu of
         Just u -> yield $ ModReqLogin u
         Nothing -> error "TODO: Handle this situation"
```

The above approach works OK, however, notice how we have to pass around
the username as payload for both the `UIEventInputUsername` and
`UIEventLogin` UI events, which leads to a bit of repetition.
Presumably, one would instead prefer to write something like this, where
the username that needs to be logged in is read from the current model
at the time the event was fired.

``` haskell
-- Processor converting UI events to model change requests.
procUIEvent' :: Model -> Processor (ReaderT () IO) UIEvent ModReq
procUIEvent' model = Processor $ \case
    UIEventInputUsername t -> yield $ ModReqSetInputUsername t
    UIEventLogin -> do
       let username = _modelInputUsername model -- new line here
       mu <- liftIO $ getUserByUsername username
       case mu of
          Just u -> yield $ ModReqLogin u
          Nothing -> error "TODO: Handle this situation"
```

I'm not 100% certain about the concurrency considerations that need to
be kept in mind to implement this, but it looks like this should be
possible. What do you think?

**Comment by k0001** [comment]
Oh, and yes, that `ReaderT` and the `Model ->` surely need to be integrated, though I'm inclined to drop that `ReaderT ()` altogether. But that's another discussion.

**Comment by commandodev** [comment]
The consideration here is that the events (or actually I guess we're more used to calling these commands) that the UI fire off should contain all the information necessary to process them. Having access to the model feels a bit dirty as I'd like the events to stand alone as their own stream.

The model is availiable in the rendering function (or at least whatever part of the model you want to make available).

The ReaderT was just a quick shim to allow the Processor to retrieve some config about where to save events. If you look in the chat example it's used to grab the socket io instance. I guess we could make the Component more monad agnostic...

**Comment by k0001** [comment]
Well, but that's kind of my point: in the rendering function you would have to talk about `_modelInputUsername` twice: once for setting it, and once for reading from it and passing it around, which to me feels dirtier than having read only access to the model in the processor function. I'm afraid this redundancy will escalate quickly when you have to deal with larger and larger inputs, leading to much boilerplate.

Anyway, I haven't used oHm as much so as to make a strong argument about all this, but I wanted to bring it up. As I continue using oHm beyond toy examples, I'll attempt a different alternative than the current one and see how it works.

**Comment by commandodev** [comment]
Hmm, point taken! I'm pretty open to both to be honest, still very much exploring the design space so do let me know how you get on :-)
