### ISSUE TITLE
missing mvc dep

### ISSUE THREAD

**Issue by joelburget** [boothead/oHm#4]
Running `nix-shell -I .` I get the following error.

```
error: getting attributes of path ‘/Users/joel/haskell/oHm/deps/mvc’: No such file or directory
```

`deps/mvc` is indeed not there. Perhaps there should be a submodule?

**Comment by k0001** [comment]
@joelburget the `mvc` version in Hackage/Nix now works out of the box, so that line should be just removed. I'll push a quick fix right away. Thanks for the reminder!

**Comment by k0001** [comment]
I made that change in https://github.com/boothead/oHm/commit/23c1711c19823c308b14a2fc89e5d96f9fb5c5cb

**Comment by commandodev** [comment]
Cheers @k0001!
